apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronbot
      role: web
  template:
    metadata:
      labels:
        app: ronbot
        role: web
    spec:
      containers:
      - name: ronbot
        image: ronbot:latest
